services:
  postgresql:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: blueskybluesky
      POSTGRES_PASSWORD: blueskybluesky
      POSTGRES_DB: blueskybluesky
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  redis:
    image: redis:7.4.1-alpine
    ports:
      - 6379:6379
volumes:
  postgresql_data:
